#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys, io, re

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

MD_PATH = r'g:/projects/mona_engine_/MonaEngine/Memorias/Memoria_Agustin_Matthey/Memoria_Agustin_Matthey.md'

with open(MD_PATH, 'r', encoding='utf-8') as f:
    text = f.read()

def rep(old, new):
    global text
    if old not in text:
        print(f'WARNING not found: {repr(old[:70])}')
    else:
        text = text.replace(old, new)

# PUA bracket chars used by the PDF math font
PUA_TOP_L  = '\uf8ee'   # ⎛ top of large (
PUA_MID_L  = '\uf8ef'   # ⎜ middle extension
PUA_BOT_L  = '\uf8f0'   # ⎝ bottom of large (
PUA_TOP_R  = '\uf8f9'   # ⎞ top of large )
PUA_MID_R  = '\uf8fa'   # ⎟ middle extension
PUA_BOT_R  = '\uf8fb'   # ⎠ bottom of large )
COMB_ARROW = '\u20d7'   # ⃗  combining right arrow above
HAT        = '\u02c6'   # ˆ  modifier letter circumflex accent
MACRON_HAT = '\u02c7'   # ˇ  (not used here)

# ── STEP 1: CID glyph artifacts ──────────────────────────────────────────────
text = text.replace('(cid:88)', '∑')
text = text.replace('(cid:89)', '∏')
text = text.replace('(cid:80)', '∑')
text = text.replace('(cid:34)', '[')
text = text.replace('(cid:35)', ']')
text = text.replace('(cid:104)', '[')
text = text.replace('(cid:105)', ']')

# Strip PUA bracket chars (they wrap display equations we'll replace with LaTeX)
for c in [PUA_TOP_L, PUA_MID_L, PUA_BOT_L, PUA_TOP_R, PUA_MID_R, PUA_BOT_R]:
    text = text.replace(c, '')

# ── STEP 2: Section 2.4.2 – FK equation (lines 595-618) ──────────────────────
rep(
'Considérese una cadena articulada con articulaciones j ,...,j ,...,j , cada una con una trans-\n'
'1 i n\n'
'formación M asociada , donde la articulacíon j es la base de la cadena y j es el end-effector.\n'
'i 1 n\n'
'Para cada transformación M , variable en el tiempo, se cumple que M (t) = T (t)R (t)S (t),\n'
'i i i i i\n'
'donde T ,R ,S son las subtransformaciones de traslacíon, rotación y escalamiento respecti-\n'
'i i i\n'
'vamente. T y S se mantienen fijas para mantener las distancias relativas, y R es variable\n'
'i i i\n'
'en el tiempo, por lo que M (t) = T R (t)S . La posicíon del end-effector en el espacio padre\n'
'i i i i\n'
'de la base de la cadena se calcula como:\n'
'[ ]\n'
'n\n'
'∏\n'
'Pos (t) = T R (t)S p\u20d7 (2.2)\n'
'ee i i i\n'
'i=1\n'
'El vector p\u20d7 = {0,0,0,1}, es la posición del end-effector en su propio espacio local. Dado\n'
'que el end-effector se encuentra en el origen de su propio sistema de referencia, aplicarle\n'
'una rotacíon a su posicíon local no genera en ella ningún cambio. Para cualquier matriz\n'
'de rotacíon R, se cumple que p\u20d7 = Rp\u20d7. Esto implica que modificar la rotación asociada al\n'
'end-effector, no altera el resultado de la ecuación 2.2.',
'Considérese una cadena articulada con articulaciones $j_1, \\ldots, j_i, \\ldots, j_n$, cada una con una transformación $M_i$ asociada, donde la articulación $j_1$ es la base de la cadena y $j_n$ es el end-effector. Para cada transformación $M_i$, variable en el tiempo, se cumple que $M_i(t) = T_i(t) R_i(t) S_i(t)$, donde $T_i, R_i, S_i$ son las subtransformaciones de traslacíon, rotación y escalamiento respectivamente. $T_i$ y $S_i$ se mantienen fijas para mantener las distancias relativas, y $R_i$ es variable en el tiempo, por lo que $M_i(t) = T_i R_i(t) S_i$. La posicíon del end-effector en el espacio padre de la base de la cadena se calcula como:\n'
'\n'
'$$\\text{Pos}_{ee}(t) = \\prod_{i=1}^n T_i R_i(t) S_i \\, \\vec{p} \\tag{2.2}$$\n'
'\n'
'El vector $\\vec{p} = \\{0,0,0,1\\}$, es la posición del end-effector en su propio espacio local. Dado que el end-effector se encuentra en el origen de su propio sistema de referencia, aplicarle una rotacíon a su posicíon local no genera en ella ningún cambio. Para cualquier matriz de rotacíon $R$, se cumple que $\\vec{p} = R\\vec{p}$. Esto implica que modificar la rotación asociada al end-effector, no altera el resultado de la ecuación 2.2.'
)

# ── STEP 3: Section 2.4.3 – IK formulation (lines 630-648) ──────────────────
rep(
'\u20d7\n'
'Defínase θ, como el vector que contiene un ángulo θ por cada articulación j de la cadena\n'
'i i\n'
'K, que indica cuanto ha rotado j desde su estado de reposo en un determinado plano de\n'
'\n'
'\u20d7\n'
'rotación. El vector θ permite determinar completamente el estado de la cadena, teníendose\n'
'como base las distancias fijas entre las articulaciones. Con cinemática directa (FK) puede\n'
'tomarse esta informacíon rotacional, y obtenerse la posición del end-effector en el espacio\n'
'de la base de la cadena. Se puede expresar entonces la posición del end-effector en función\n'
'\u20d7\n'
'de las rotaciones de las articulaciones como \u20d7s = f(θ), usando FK. Resolver el problema de\n'
'IK consiste en obtener la función inversa, tal que\n'
'f−1(\u20d7s)\n'
'= θ\n'
'\u20d7\n'
'.\n'
'f−1\n'
'es una función altamente',
'Defínase $\\vec{\\theta}$, como el vector que contiene un ángulo $\\theta_i$ por cada articulación $j_i$ de la cadena K, que indica cuanto ha rotado $j$ desde su estado de reposo en un determinado plano de rotación. El vector $\\vec{\\theta}$ permite determinar completamente el estado de la cadena, teníendose como base las distancias fijas entre las articulaciones. Con cinemática directa (FK) puede tomarse esta informacíon rotacional, y obtenerse la posición del end-effector en el espacio de la base de la cadena. Se puede expresar entonces la posición del end-effector en función de las rotaciones de las articulaciones como $\\vec{s} = f(\\vec{\\theta})$, usando FK. Resolver el problema de IK consiste en obtener la función inversa, tal que\n'
'\n'
'$$f^{-1}(\\vec{s}) = \\vec{\\theta}$$\n'
'\n'
'$f^{-1}$ es una función altamente'
)

# ── STEP 4: Section 2.5 – LIC interpolation formula (lines 680-713) ─────────
rep(
'Una curva linealmente\n'
'interpolada es en realidad una spline lineal [21]. Si una LIC l posee k puntos p , con sus\n'
'\n'
'respectivos valores del parámetro t, t ,...,t ,...,t , se genera un intervalo de tiempo [t ,t ] para\n'
'1 i k 1 k\n'
'l. Es posible obtener un punto de la curva para cualquier instante de tiempo\n'
't\u02c6perteneciente\n'
'a\n'
'ese intervalo, simulando continuidad. Si se da que ∃i\n'
't\u02c6=\n'
't , entonces obtenemos directamente\n'
'\n'
'el punto asociado a t y\n'
'l(t\u02c6)\n'
'= p . En otro caso, buscamos el subintervalo más pequeño que\n'
'i i\n'
'contenga a\n'
't\u02c6,\n'
'tal que t <\n'
't\u02c6\n'
'< t e interpolamos linealmente entre los puntos p y p\n'
'i i+1 i i+1\n'
'utilizando la relacíon entre t ,\n'
't\u02c6\n'
'y t como referencia, obteníendose que:\n'
'i i+1\n'
't\u02c6−\n'
't\n'
'l(t\u02c6)\n'
'= p + (p − p )\n'
'\n'
'i i+1 i\n'
't − t\n'
'i+1 i',
'Una curva linealmente interpolada es en realidad una spline lineal [21]. Si una LIC $l$ posee $k$ puntos $p_i$, con sus respectivos valores del parámetro $t$, $t_1, \\ldots, t_i, \\ldots, t_k$, se genera un intervalo de tiempo $[t_1, t_k]$ para $l$. Es posible obtener un punto de la curva para cualquier instante de tiempo $\\hat{t}$ perteneciente a ese intervalo, simulando continuidad. Si se da que $\\exists\\, i: \\hat{t} = t_i$, entonces obtenemos directamente el punto asociado a $t_i$ y $l(\\hat{t}) = p_i$. En otro caso, buscamos el subintervalo más pequeño que contenga a $\\hat{t}$, tal que $t_i < \\hat{t} < t_{i+1}$ e interpolamos linealmente entre los puntos $p_i$ y $p_{i+1}$ utilizando la relacíon entre $t_i$, $\\hat{t}$ y $t_{i+1}$ como referencia, obteníendose que:\n'
'\n'
'$$l(\\hat{t}) = p_i + (p_{i+1} - p_i)\\,\\frac{\\hat{t} - t_i}{t_{i+1} - t_i}$$'
)

# ── STEP 5: Section 2.6 – Gradient descent formula (lines 717-743) ───────────
# Note: PUA chars already stripped above; blank lines remain where they were
rep(
'El descenso de gradiente [5] es una técnica de optimizacíon iterativa, que permite en-\n'
'contrar mínimos locales en una función escalar, multivariable, y diferenciable. Si se tiene\n'
'una función F, que cumple con las características anteriores, se quiere encontrar un vector\n'
'\u20d7x = {x ,...,x ,...,x } tal que F(\u20d7x) sea un mínimo local. En cada iteración debe calcularse el\n'
'1 i n\n'
'gradiente de F evaluado en \u20d7x:\n'
' \n'
'∂F(\u20d7x)\n'
'∂x1\n'
'\n'
'...\n'
'\n'
' \n'
'∇F(\u20d7x) =\n'
'∂F(\u20d7x)\n'
'\n'
'\n'
'∂xi\n'
'\n'
'\n'
'...\n'
' \n'
'∂F(\u20d7x)\n'
'∂xn\n'
'El gradiente de F evaluado en \u20d7x es un vector, e indica la dirección de máximo crecimiento\n'
'de F. Teniendo calculado el gradiente, se actualiza el valor de \u20d7x:\n'
'\u20d7x := \u20d7x − λ∇F(\u20d7x)',
'El descenso de gradiente [5] es una técnica de optimizacíon iterativa, que permite encontrar mínimos locales en una función escalar, multivariable, y diferenciable. Si se tiene una función $F$, que cumple con las características anteriores, se quiere encontrar un vector $\\vec{x} = \\{x_1, \\ldots, x_i, \\ldots, x_n\\}$ tal que $F(\\vec{x})$ sea un mínimo local. En cada iteración debe calcularse el gradiente de $F$ evaluado en $\\vec{x}$:\n'
'\n'
'$$\\nabla F(\\vec{x}) = \\begin{pmatrix} \\dfrac{\\partial F(\\vec{x})}{\\partial x_1} \\\\ \\vdots \\\\ \\dfrac{\\partial F(\\vec{x})}{\\partial x_i} \\\\ \\vdots \\\\ \\dfrac{\\partial F(\\vec{x})}{\\partial x_n} \\end{pmatrix}$$\n'
'\n'
'El gradiente de $F$ evaluado en $\\vec{x}$ es un vector, e indica la dirección de máximo crecimiento de $F$. Teniendo calculado el gradiente, se actualiza el valor de $\\vec{x}$:\n'
'\n'
'$$\\vec{x} := \\vec{x} - \\lambda\\nabla F(\\vec{x})$$'
)

# ── STEP 6a: Section 3.1.2 – Jacobian paragraph (lines 943-988) ──────────────
rep(
'Recordando el planteamiento original de IK (2.4.3), se busca solucionar la ecuación\n'
'f−1(\u20d7s)\n'
'=\n'
'\u20d7 \u20d7\n'
'θ. Generalizando, θ es el vector de rotaciones, y \u20d7s es un vector con las posiciones de un\n'
'número arbitrario end-effectors. Si se considera \u20d7s como las posiciones actuales, y\n'
'\u20d7t\n'
'como las\n'
'posiciones objetivo, se puede definir un vector de error \u20d7e, tal que \u20d7e =\n'
'\u20d7t−\u20d7s.\n'
'Se quiere usar los\n'
'métodos numéricos para modificar \u20d7s, acercándolo a\n'
'\u20d7t\n'
'lo más posible y minimizando el error\n'
'\u20d7e.\n'
'Métodos basados en la inversíon del Jacobiano\n'
'Se puede escribir el jacobiano del vector θ como J(θ\n'
'\u20d7\n'
') =\n'
'(∂si\n'
') . Las entradas de la\n'
'ij\n'
'∂θj\n'
'ij\n'
'matriz J pueden calcularse como\n'
'(∂s\u20d7i\n'
') = v × (s\u20d7 − p\u20d7 ), donde v\u20d7 es el vector unitario\n'
'∂θj\n'
'ij j i j j\n'
'que apunta en la direccíon del eje actual de rotacíon de la j-ésima articulación, y p\u20d7 es\n'
'j\n'
'su posición actual. Además la derivada de \u20d7s con respecto al tiempo puede escribirse como\n'
'˙\n'
'˙\n'
'\u20d7 \u20d7\n'
'\u20d7s = J(θ)θ. Con esto, una pequeña variación del vector \u20d7s puede aproximarse como ∆\u20d7s ≈\n'
'\u20d7 \u20d7\n'
'J∆θ. La idea es elegir un vector ∆θ que haga que ∆\u20d7s se aproxime lo más posible a \u20d7e,\n'
'logrando así un acercamiento a la posicíon objetivo con ese pequeño cambio. Por último,\n'
'\u20d7\n'
'se puede obtener la variación de θ requerida si se calcula el inverso del jacobiano J, ya que\n'
'∆θ\n'
'\u20d7\n'
'=\n'
'J−1\u20d7e.\n'
'Para resolver esta ecuacíon en general se buscan alternativas que eviten tener',
'Recordando el planteamiento original de IK (2.4.3), se busca solucionar la ecuación $f^{-1}(\\vec{s}) = \\vec{\\theta}$. Generalizando, $\\vec{\\theta}$ es el vector de rotaciones, y $\\vec{s}$ es un vector con las posiciones de un número arbitrario end-effectors. Si se considera $\\vec{s}$ como las posiciones actuales, y $\\vec{t}$ como las posiciones objetivo, se puede definir un vector de error $\\vec{e}$, tal que $\\vec{e} = \\vec{t} - \\vec{s}$. Se quiere usar los métodos numéricos para modificar $\\vec{s}$, acercándolo a $\\vec{t}$ lo más posible y minimizando el error $\\vec{e}$.\n'
'\n'
'**Métodos basados en la inversíon del Jacobiano**\n'
'\n'
'Se puede escribir el jacobiano del vector $\\vec{\\theta}$ como $J(\\vec{\\theta}) = \\left(\\dfrac{\\partial s_i}{\\partial \\theta_j}\\right)_{ij}$. Las entradas de la matriz $J$ pueden calcularse como $\\left(\\dfrac{\\partial \\vec{s}_i}{\\partial \\theta_j}\\right)_{ij} = \\vec{v}_j \\times (\\vec{s}_i - \\vec{p}_j)$, donde $\\vec{v}_j$ es el vector unitario que apunta en la dirección del eje actual de rotación de la $j$-ésima articulación, y $\\vec{p}_j$ es su posición actual. Además la derivada de $\\vec{s}$ con respecto al tiempo puede escribirse como $\\dot{\\vec{s}} = J(\\vec{\\theta})\\dot{\\vec{\\theta}}$. Con esto, una pequeña variación del vector $\\vec{s}$ puede aproximarse como $\\Delta\\vec{s} \\approx J\\Delta\\vec{\\theta}$. La idea es elegir un vector $\\Delta\\vec{\\theta}$ que haga que $\\Delta\\vec{s}$ se aproxime lo más posible a $\\vec{e}$, logrando así un acercamiento a la posicíon objetivo con ese pequeño cambio. Por último, se puede obtener la variación de $\\vec{\\theta}$ requerida si se calcula el inverso del jacobiano $J$, ya que $\\Delta\\vec{\\theta} = J^{-1}\\vec{e}$. Para resolver esta ecuacíon en general se buscan alternativas que eviten tener'
)

# ── STEP 6b: Jacobian transpose method (lines 999-1034) ──────────────────────
rep(
'i Transpuesta del jacobiano: Se modifica la ecuacíon para reemplazar\n'
'J−1,\n'
'quedando como\n'
'∆θ\n'
'\u20d7\n'
'=\n'
'αJT\u20d7e,\n'
'donde\n'
'JT\n'
'es la transpuesta de J y α es un escalar que puede calcularse como\n'
'α =\n'
'\u20d7e·JJT\u20d7e\n'
', siendo · el producto punto. Esta solución suele requerir muchas iteraciones\n'
'JJT\u20d7e·JJT\u20d7e\n'
'\u20d7\n'
'(cálculos consecutivos de valores pequeños ∆θ) para acercarse de forma aceptable al\n'
'objetivo\n'
'\u20d7t,\n'
'y es común que genere poses poco creíbles y movimientos faltos de fluidez.\n'
'Estos problemas se dan principalmente cuando el objetivo esta muy lejos de la posicíon\n'
'inicial. Para evitar problemas es tambíen ideal que el valor de α sea pequeño.\n'
'ii Pseudo-inversa del jacobiano: En este caso la ecuacíon es ∆θ\n'
'\u20d7\n'
'=\n'
'αJpi\u20d7e,\n'
'donde\n'
'Jpi\n'
'es la\n'
'pseudo-inversa del jacobiano o inversa Moore-Penrose. La pseudo-inversa puede calcularse\n'
'como\n'
'Jpi\n'
'=\n'
'JT(JJT)−1.\n'
'Esta solución, en caso de estar cerca de una singularidad es\n'
'especialmente propensa a generar cambios drásticos en los ángulos de las articulaciones\n'
'aunque el cambio en la posicíon del end-effector sea muy pequeño.',
'i) **Transpuesta del jacobiano:** Se modifica la ecuacíon para reemplazar $J^{-1}$, quedando como $\\Delta\\vec{\\theta} = \\alpha J^T\\vec{e}$, donde $J^T$ es la transpuesta de $J$ y $\\alpha$ es un escalar que puede calcularse como\n'
'\n'
'$$\\alpha = \\frac{\\vec{e} \\cdot JJ^T\\vec{e}}{JJ^T\\vec{e} \\cdot JJ^T\\vec{e}}$$\n'
'\n'
'siendo $\\cdot$ el producto punto. Esta solución suele requerir muchas iteraciones (cálculos consecutivos de valores pequeños $\\Delta\\vec{\\theta}$) para acercarse de forma aceptable al objetivo $\\vec{t}$, y es común que genere poses poco creíbles y movimientos faltos de fluidez. Estos problemas se dan principalmente cuando el objetivo esta muy lejos de la posicíon inicial. Para evitar problemas es tambíen ideal que el valor de $\\alpha$ sea pequeño.\n'
'\n'
'ii) **Pseudo-inversa del jacobiano:** En este caso la ecuacíon es $\\Delta\\vec{\\theta} = \\alpha J_{pi}\\vec{e}$, donde $J_{pi}$ es la pseudo-inversa del jacobiano o inversa Moore-Penrose. La pseudo-inversa puede calcularse como $J_{pi} = J^T(JJ^T)^{-1}$. Esta solución, en caso de estar cerca de una singularidad es especialmente propensa a generar cambios drásticos en los ángulos de las articulaciones aunque el cambio en la posicíon del end-effector sea muy pequeño.'
)

# ── STEP 6c: Eq 3.1 ──────────────────────────────────────────────────────────
rep(
'ejemplo, usarse la siguiente función:\n'
'F(θ\n'
'\u20d7\n'
') = ||\u20d7s(θ\n'
'\u20d7\n'
')\n'
'−\u20d7t||2\n'
'(3.1)',
'ejemplo, usarse la siguiente función:\n'
'\n'
'$$F(\\vec{\\theta}) = ||\\vec{s}(\\vec{\\theta}) - \\vec{t}||^2 \\tag{3.1}$$'
)

# ── STEP 7: Section 4.5 – GD implementation (lines 1680-1741) ────────────────
rep(
'función final a la que se aplicará la técnica de descenso de gradiente. Considérese que se quiere\n'
'aplicar la técnica a las funciones f ,...,f ,...,f en conjunto, ya que cada una de ellas tiene\n'
'1 i n\n'
'un significado en el contexto del problema a resolver. Estas funciones dependen del mismo\n'
'vector de variables \u20d7x = {x ,...,x ,...,x }. Se construye una función total F(\u20d7x) =\n'
'∑n\n'
'f (\u20d7x),\n'
'1 k m\n'
'i=1\n'
'\n'
'a la que finalmente se aplica el descenso de gradiente. Cada subfunción (o término) f , se\n'
'\n'
'\u20d7\n'
'encapsula en un FunctionTerm que permite calcular su valor f (x\u02c6), y su derivada parcial\n'
'\n'
'∂fi(\u20d7x\u02c6).\n'
'Cada término tiene tambíen asignado un peso w , que determina su importancia para\n'
'∂x\u02c6\n'
'\n'
'k\n'
'el cálculo del valor final.\n'
'\n'
'\n'
'La clase GradientDescent utiliza la funcíon de derivada parcial en cada término para\n'
'construir el vector gradiente:\n'
' \n'
'∂fi(\u20d7x)\n'
'∂x1\n'
' ... \n'
'∑\n'
'n\n'
' \n'
'∇F(\u20d7x) = w\n'
'∂fi(\u20d7x)\n'
'i \n'
'∂x\n'
'\n'
'\n'
'k\n'
'\n'
'i=1\n'
'...\n'
' \n'
'∂fi(\u20d7x)\n'
'∂xm\n'
'Recordando lo expuesto en 2.6, el vector \u20d7x que minimiza localmente la función F se actualiza\n'
'como sigue:\n'
'\u20d7x := \u20d7x − λ∇F(\u20d7x)\n'
'Esta es la forma regular de actualizar el gradiente, pero existen muchas variantes. La clase\n'
'GradientDescent, además del método regular, puede utilizar la técnica de descenso de gra-\n'
'diente con momentum, en que los cálculos de iteraciones pasadas tienen un peso en el cálculo\n'
'del valor actual del gradiente. El valor almacenado del gradiente, ∇F(\u20d7x) , se actualiza de\n'
'saved\n'
'la siguiente manera utilizando momentum:\n'
'∇F(\u20d7x) := α∇F(\u20d7x) + (1 − α)∇F(\u20d7x)\n'
'saved saved\n'
'α es el factor que indica cúanto pesa el gradiente histórico ∇F(\u20d7x) , en relación al gradiente\n'
'saved\n'
'calculado en la iteracíon actual ∇F(\u20d7x). En este caso particular, se utiliza α = 0,8. El vector\n'
'\u20d7x se actualiza como sigue usando momentum:\n'
'\u20d7x := \u20d7x − λ∇F(\u20d7x)\n'
'saved',
'función final a la que se aplicará la técnica de descenso de gradiente. Considérese que se quiere aplicar la técnica a las funciones $f_1, \\ldots, f_i, \\ldots, f_n$ en conjunto, ya que cada una de ellas tiene un significado en el contexto del problema a resolver. Estas funciones dependen del mismo vector de variables $\\vec{x} = \\{x_1, \\ldots, x_k, \\ldots, x_m\\}$. Se construye una función total\n'
'\n'
'$$F(\\vec{x}) = \\sum_{i=1}^n f_i(\\vec{x})$$\n'
'\n'
'a la que finalmente se aplica el descenso de gradiente. Cada subfunción (o término) $f_i$ se encapsula en un FunctionTerm que permite calcular su valor $f_i(\\hat{\\vec{x}})$, y su derivada parcial $\\dfrac{\\partial f_i(\\hat{\\vec{x}})}{\\partial \\hat{x}_k}$. Cada término tiene tambíen asignado un peso $w_i$, que determina su importancia para el cálculo del valor final.\n'
'\n'
'La clase GradientDescent utiliza la funcíon de derivada parcial en cada término para construir el vector gradiente:\n'
'\n'
'$$\\nabla F(\\vec{x}) = \\sum_{i=1}^n w_i \\begin{pmatrix} \\dfrac{\\partial f_i(\\vec{x})}{\\partial x_1} \\\\ \\vdots \\\\ \\dfrac{\\partial f_i(\\vec{x})}{\\partial x_k} \\\\ \\vdots \\\\ \\dfrac{\\partial f_i(\\vec{x})}{\\partial x_m} \\end{pmatrix}$$\n'
'\n'
'Recordando lo expuesto en 2.6, el vector $\\vec{x}$ que minimiza localmente la función $F$ se actualiza como sigue:\n'
'\n'
'$$\\vec{x} := \\vec{x} - \\lambda\\nabla F(\\vec{x})$$\n'
'\n'
'Esta es la forma regular de actualizar el gradiente, pero existen muchas variantes. La clase GradientDescent, además del método regular, puede utilizar la técnica de descenso de gradiente con momentum, en que los cálculos de iteraciones pasadas tienen un peso en el cálculo del valor actual del gradiente. El valor almacenado del gradiente, $\\nabla F(\\vec{x})_{saved}$, se actualiza de la siguiente manera utilizando momentum:\n'
'\n'
'$$\\nabla F(\\vec{x})_{saved} := \\alpha\\nabla F(\\vec{x})_{saved} + (1 - \\alpha)\\nabla F(\\vec{x})$$\n'
'\n'
'$\\alpha$ es el factor que indica cúanto pesa el gradiente histórico $\\nabla F(\\vec{x})_{saved}$, en relación al gradiente calculado en la iteracíon actual $\\nabla F(\\vec{x})$. En este caso particular, se utiliza $\\alpha = 0{,}8$. El vector $\\vec{x}$ se actualiza como sigue usando momentum:\n'
'\n'
'$$\\vec{x} := \\vec{x} - \\lambda\\nabla F(\\vec{x})_{saved}$$'
)

# ── STEP 8: Section 4.6.2 – IK function terms ────────────────────────────────

# Eq 4.1
rep(
'es:\n'
'f (θ\n'
'\u20d7\n'
') = ||eeP\n'
'\u20d7\n'
'os(θ\n'
'\u20d7\n'
') − eeTa\n'
'\u20d7\n'
'rget||2\n'
'(4.1)\n'
'\n'
'\u20d7 \u20d7 \u20d7\n'
'Donde eePos(θ) es la posición actual del end-effector, y eeTarget es la posición a la que',
'es:\n'
'\n'
'$$f_1(\\vec{\\theta}) = ||\\overrightarrow{eePos}(\\vec{\\theta}) - \\overrightarrow{eeTarget}\\,||^2 \\tag{4.1}$$\n'
'\n'
'Donde $\\overrightarrow{eePos}(\\vec{\\theta})$ es la posición actual del end-effector, y $\\overrightarrow{eeTarget}$ es la posición a la que'
)

# Eq 4.2
rep(
'\u20d7\n'
'constantes. Notar primero que eePos(θ) puede descomponerse de la siguiente manera:\n'
'eeP\n'
'\u20d7\n'
'os(θ\n'
'\u20d7\n'
') = M\n'
'\u02c7\n'
'AT\u03b8 kR\u03b8 kS\u03b8\n'
'kM\n'
'\u02c7\n'
'B\n'
'\u20d7\n'
'\u02c7\n'
'b (4.2)',
'constantes. Notar primero que $\\overrightarrow{eePos}(\\vec{\\theta})$ puede descomponerse de la siguiente manera:\n'
'\n'
'$$\\overrightarrow{eePos}(\\vec{\\theta}) = \\hat{M}_A T_{\\theta_k} R_{\\theta_k} S_{\\theta_k} \\hat{M}_B \\hat{\\vec{b}} \\tag{4.2}$$'
)

# Eq 4.3
rep(
'constantes, quedando\n'
'MA\n'
'= M\n'
'\u02c7\n'
'AT\u03b8\n'
'k\n'
'y\n'
'\u20d7\n'
'b =\n'
'S\u03b8\n'
'kM\n'
'\u02c7\n'
'B\n'
'\u20d7\n'
'\u02c7\n'
'b = {b ,b ,b ,b }:\n'
'0 1 2 3\n'
'eeP\n'
'\u20d7\n'
'os(θ\n'
'\u20d7\n'
') =\n'
'MAR\u03b8\n'
'k\n'
'\u20d7\n'
'b (4.3)',
'constantes, quedando $M_A = \\hat{M}_A T_{\\theta_k}$ y $\\vec{b} = S_{\\theta_k} \\hat{M}_B \\hat{\\vec{b}} = \\{b_0, b_1, b_2, b_3\\}$:\n'
'\n'
'$$\\overrightarrow{eePos}(\\vec{\\theta}) = M_A R_{\\theta_k} \\vec{b} \\tag{4.3}$$'
)

# Eq 4.4 — note: PUA chars already stripped; remaining structure:
rep(
'Los elementos de los factores de la ecuación 4.3 se agrupan con sumatorias:\n'
' \n'
'b\n'
'MAR\u03b8\n'
'k\n'
'j\n'
'0i ij\n'
'∑\n'
'\n'
'∑\n'
'\n'
'b\n'
'MAR\u03b8\n'
'k\n'
'eeP\n'
'\u20d7\n'
'os(θ\n'
'\u20d7\n'
') =\n'
'\n'
'j\n'
'1i\n'
'ij\n'
'\n'
'(4.4)\n'
'b\n'
'MAR\u03b8\n'
'k\n'
'\n'
'j=0 i=0\n'
' j\n'
'2i ij\n'
'\n'
'b\n'
'MAR\u03b8\n'
'k\n'
'j\n'
'3i ij',
'Los elementos de los factores de la ecuación 4.3 se agrupan con sumatorias:\n'
'\n'
'$$\\overrightarrow{eePos}(\\vec{\\theta}) = \\begin{pmatrix} \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{0i}\\, b_{ij} \\\\ \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{1i}\\, b_{ij} \\\\ \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{2i}\\, b_{ij} \\\\ \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{3i}\\, b_{ij} \\end{pmatrix} \\tag{4.4}$$'
)

# Eq 4.5 — need to verify exact PUA-stripped form; check lines 1965-2012
rep(
'Substrayendo la posicíon objetivo:\n'
' \n'
'b\n'
'MAR\u03b8\n'
'k −\n'
'eeTarget0\n'
'j\n'
'0i ij\n'
'\n'
'∑\n'
'\n'
'∑\n'
'\n'
'b\n'
'MAR\u03b8\n'
'k\n'
'−\n'
'eeTarget1\n'
'eeP\n'
'\u20d7\n'
'os(θ\n'
'\u20d7\n'
') − eeTa\n'
'\u20d7\n'
'rget =\n'
'\n'
'j\n'
'1i ij\n'
'\n'
'\n'
'(4.5)\n'
'b\n'
'MAR\u03b8\n'
'k\n'
'−\n'
'eeTarget2\n'
'\n'
'j=0 i=0\n'
' j\n'
'2i ij\n'
'\n'
'\n'
'b\n'
'MAR\u03b8\n'
'k −\n'
'eeTarget3\n'
'j\n'
'3i ij',
'Substrayendo la posicíon objetivo:\n'
'\n'
'$$\\overrightarrow{eePos}(\\vec{\\theta}) - \\overrightarrow{eeTarget} = \\begin{pmatrix} \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{0i}\\, b_{ij} - eeTarget_0 \\\\ \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{1i}\\, b_{ij} - eeTarget_1 \\\\ \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{2i}\\, b_{ij} - eeTarget_2 \\\\ \\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{3i}\\, b_{ij} - eeTarget_3 \\end{pmatrix} \\tag{4.5}$$'
)

# Eq 4.6
rep(
'Finalmente la funcíon f reconstruida queda de la siguiente forma:\n'
'\n'
'[ ]2\n'
'3 3 3\n'
'∑ ∑∑\n'
'eeTarget\n'
'f (θ\n'
'\u20d7\n'
') = (b\n'
'MAR\u03b8\n'
'k −\n'
'k\n'
') (4.6)\n'
'1 j\n'
'ki ij\n'
'\n'
'k=0 j=0 i=0',
'Finalmente la funcíon $f_1$ reconstruida queda de la siguiente forma:\n'
'\n'
'$$f_1(\\vec{\\theta}) = \\sum_{k=0}^{3} \\left[\\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{ki}\\, b_{ij} - eeTarget_k\\right]^2 \\tag{4.6}$$'
)

# Eq 4.7
rep(
'Con esto, la parte variable de f queda claramente separada en\n'
'R\u03b8\n'
'k, y calcular la\n'
'\n'
'ij\n'
'derivada parcial resulta más fácil:\n'
'[ ]\n'
'∂f (θ\n'
'\u20d7\n'
')\n'
'∑\n'
'\n'
'∑\n'
'\n'
'∑\n'
'\n'
'eeTarget\n'
'∑\n'
'\n'
'∑\n'
'3 ∂R\u03b8\n'
'k\n'
'\n'
'= 2 (b\n'
'MAR\u03b8\n'
'k\n'
'−\n'
'k\n'
') b\n'
'MA\n'
'ij\n'
'(4.7)\n'
'∂θ\n'
'j\n'
'ki ij\n'
'\n'
'j\n'
'ki\n'
'∂θ\n'
'k k\n'
'k=0 j=0 i=0 j=0 i=0',
'Con esto, la parte variable de $f_1$ queda claramente separada en $[R_{\\theta_k}]_{ij}$, y calcular la derivada parcial resulta más fácil:\n'
'\n'
'$$\\frac{\\partial f_1(\\vec{\\theta})}{\\partial \\theta_k} = 2 \\sum_{k=0}^{3}\\sum_{j=0}^{3}\\sum_{i=0}^{3} \\left(\\sum_{j=0}^{3}\\sum_{i=0}^{3} [M_A R_{\\theta_k}]_{ki}\\, b_{ij} - eeTarget_k\\right) [M_A]_{ki}\\, \\frac{\\partial [R_{\\theta_k}]_{ij}}{\\partial \\theta_k} \\tag{4.7}$$'
)

# Eq 4.8-4.9
rep(
'La función escogida es:\n'
'f (θ\n'
'\u20d7\n'
') = ||θ\n'
'\u20d7\n'
'−\n'
'ω\u20d7||2\n'
'(4.8)\n'
'\n'
'El vector constante ω\u20d7 contiene, por cada θ , el ángulo ω original de la animacíon en\n'
'k k\n'
'el frame objetivo para la misma articulación j . La derivada es simple de calcular:\n'
'k\n'
'\u20d7\n'
'∂f (θ)\n'
'\n'
'= 2(θ − ω ) (4.9)\n'
'k k\n'
'∂θ\n'
'k',
'La función escogida es:\n'
'\n'
'$$f_2(\\vec{\\theta}) = ||\\vec{\\theta} - \\vec{\\omega}\\,||^2 \\tag{4.8}$$\n'
'\n'
'El vector constante $\\vec{\\omega}$ contiene, por cada $\\theta_k$, el ángulo $\\omega_k$ original de la animacíon en el frame objetivo para la misma articulación $j_k$. La derivada es simple de calcular:\n'
'\n'
'$$\\frac{\\partial f_2(\\vec{\\theta})}{\\partial \\theta_k} = 2(\\theta_k - \\omega_k) \\tag{4.9}$$'
)

# Eq 4.10-4.11
rep(
'Las ecuaciones\n'
'son análogas a las del segundo término:\n'
'f (θ\n'
'\u20d7\n'
') = ||θ\n'
'\u20d7\n'
'−\n'
'\u20d7γ||2\n'
'(4.10)\n'
'\n'
'En este caso, el vector constante \u20d7γ, en lugar de contener los valores originales, contiene\n'
'los valores de frame anterior para cada j .\n'
'k\n'
'\u20d7\n'
'∂f (θ)\n'
'\n'
'= 2(θ − γ ) (4.11)\n'
'k k\n'
'∂θ\n'
'k',
'Las ecuaciones son análogas a las del segundo término:\n'
'\n'
'$$f_3(\\vec{\\theta}) = ||\\vec{\\theta} - \\vec{\\gamma}\\,||^2 \\tag{4.10}$$\n'
'\n'
'En este caso, el vector constante $\\vec{\\gamma}$, en lugar de contener los valores originales, contiene los valores de frame anterior para cada $j_k$.\n'
'\n'
'$$\\frac{\\partial f_3(\\vec{\\theta})}{\\partial \\theta_k} = 2(\\theta_k - \\gamma_k) \\tag{4.11}$$'
)

# Eq 4.12
rep(
'La funcíon final F a minimizar es:\n'
'\u20d7 \u20d7 \u20d7 \u20d7\n'
'F(θ) = af (θ) + bf (θ) + cf (θ) (4.12)\n'
'1 2 3',
'La funcíon final $F$ a minimizar es:\n'
'\n'
'$$F(\\vec{\\theta}) = a\\,f_1(\\vec{\\theta}) + b\\,f_2(\\vec{\\theta}) + c\\,f_3(\\vec{\\theta}) \\tag{4.12}$$'
)

# Coeff a value
rep(
'Los valores usados son a =\n'
'\n'
', b = 2, y c = 4. El valor rigHeight corresponde a\n'
'[rigHeight][δp]',
'Los valores usados son $a = \\dfrac{1}{rigHeight \\cdot \\delta_p}$, $b = 2$, y $c = 4$. El valor $rigHeight$ corresponde a'
)

# Eq 4.13-4.14
rep(
'alcanzada, se calcula como δp =\n'
'2lsin(δθ).\n'
'Al ser δθ pequeño, puede aproximarse la función\n'
'\n'
'seno a su argumento, con lo que δp ≈ lδθ. Reordenando y considerando el cuadrado de la\n'
'distancia:\n'
'δp\n'
'l ≈ (4.13)\n'
'δθ\n'
'δp2\n'
'lδp ≈ (4.14)\n'
'δθ',
'alcanzada, se calcula como $\\delta p = 2l\\sin(\\delta\\theta)$. Al ser $\\delta\\theta$ pequeño, puede aproximarse la función seno a su argumento, con lo que $\\delta p \\approx l\\delta\\theta$. Reordenando y considerando el cuadrado de la distancia:\n'
'\n'
'$$l \\approx \\frac{\\delta p}{\\delta\\theta} \\tag{4.13}$$\n'
'\n'
'$$l\\,\\delta p \\approx \\frac{\\delta p^2}{\\delta\\theta} \\tag{4.14}$$'
)

# init theta = gamma
rep(
'se escoge entonces inicializar el vector de variables como\n'
'sigue:\n'
'\u20d7\n'
'θ = \u20d7γ',
'se escoge entonces inicializar el vector de variables como sigue:\n'
'\n'
'$$\\vec{\\theta} = \\vec{\\gamma}$$'
)

# ── STEP 9: LIC velocity equations (section 4.8.1) ───────────────────────────
rep(
'donde las ecuaciones son\n'
'p\u20d7\n'
'k\n'
'−p\u20d7\n'
'k−1\n'
'y\n'
'p\u20d7\n'
'k+1\n'
'−p\u20d7\n'
'k\n'
'respectivamente.\n'
't −t t −t\n'
'k k−1 k+1 k',
'donde las ecuaciones son $\\dfrac{\\vec{p}_k - \\vec{p}_{k-1}}{t_k - t_{k-1}}$ y $\\dfrac{\\vec{p}_{k+1} - \\vec{p}_k}{t_{k+1} - t_k}$ respectivamente.'
)

# ── STEP 10: Annex B.1 – Rotation matrix ─────────────────────────────────────
rep(
'De [24] se extrae la ecuación para una matriz de 3x3, donde \u20d7a es el eje de rotación y θ el\n'
'ángulo:\n'
' \n'
'cosθ +\n'
'a2(1\n'
'− cosθ) a a (1 − cosθ) − a sinθ a a (1 − cosθ) + a sinθ\n'
'\n'
'0 1 2 0 2 1\n'
'R(θ,\u20d7a) = a\n'
'\n'
'a\n'
'\n'
'(1 − cosθ) + a\n'
'\n'
'sinθ cosθ +\n'
'a2\n'
'\n'
'(1 − cosθ) a\n'
'\n'
'a\n'
'\n'
'(1 − cosθ) − a\n'
'\n'
'sinθ\n'
'a a (1 − cosθ) − a sinθ a a (1 − cosθ) + a sinθ cosθ +\n'
'a2(1\n'
'− cosθ)\n'
'0 2 1 1 2 0\n'
'\n'
'Expandiendo a 4x4 y derivando con respecto a θ:\n'
' \n'
'−sinθ +\n'
'a2sinθ\n'
'a a sinθ − a cosθ a a sinθ + a cosθ 0\n'
'\n'
'0 1 2 0 2 1\n'
'∂R(θ,\u20d7a)\n'
'=\n'
'\n'
'\n'
'a\n'
'\n'
'a\n'
'\n'
'sinθ + a\n'
'\n'
'cosθ −sinθ +\n'
'a2\n'
'\n'
'sinθ a\n'
'\n'
'a\n'
'\n'
'sinθ − a\n'
'\n'
'cosθ 0\n'
'\n'
'∂θ\n'
'a\n'
'\n'
'a\n'
'\n'
'sinθ − a\n'
'\n'
'cosθ a\n'
'\n'
'a\n'
'\n'
'sinθ + a\n'
'\n'
'cosθ −sinθ +\n'
'a2\n'
'\n'
'sinθ 0\n'
'0 0 0 0',
'De [24] se extrae la ecuación para una matriz de 3x3, donde $\\vec{a} = (a_0, a_1, a_2)$ es el eje de rotación y $\\theta$ el ángulo:\n'
'\n'
'$$R(\\theta,\\vec{a}) = \\begin{pmatrix} \\cos\\theta + a_0^2(1-\\cos\\theta) & a_0 a_1(1-\\cos\\theta) - a_2\\sin\\theta & a_0 a_2(1-\\cos\\theta) + a_1\\sin\\theta \\\\ a_1 a_0(1-\\cos\\theta) + a_2\\sin\\theta & \\cos\\theta + a_1^2(1-\\cos\\theta) & a_1 a_2(1-\\cos\\theta) - a_0\\sin\\theta \\\\ a_2 a_0(1-\\cos\\theta) - a_1\\sin\\theta & a_2 a_1(1-\\cos\\theta) + a_0\\sin\\theta & \\cos\\theta + a_2^2(1-\\cos\\theta) \\end{pmatrix}$$\n'
'\n'
'Expandiendo a 4x4 y derivando con respecto a $\\theta$:\n'
'\n'
'$$\\frac{\\partial R(\\theta,\\vec{a})}{\\partial\\theta} = \\begin{pmatrix} -\\sin\\theta + a_0^2\\sin\\theta & a_0 a_1\\sin\\theta - a_2\\cos\\theta & a_0 a_2\\sin\\theta + a_1\\cos\\theta & 0 \\\\ a_1 a_0\\sin\\theta + a_2\\cos\\theta & -\\sin\\theta + a_1^2\\sin\\theta & a_1 a_2\\sin\\theta - a_0\\cos\\theta & 0 \\\\ a_2 a_0\\sin\\theta - a_1\\cos\\theta & a_2 a_1\\sin\\theta + a_0\\cos\\theta & -\\sin\\theta + a_2^2\\sin\\theta & 0 \\\\ 0 & 0 & 0 & 0 \\end{pmatrix}$$'
)

# ── STEP 11: Remove remaining orphaned combining-arrow lines ─────────────────
text = re.sub(r'\n\u20d7\n', '\n', text)
text = re.sub(r'^\u20d7\n', '', text, flags=re.MULTILINE)

with open(MD_PATH, 'w', encoding='utf-8') as f:
    f.write(text)

print('Done — equations converted to LaTeX.')
