/* Generated by Cython 0.29.28 */

#ifndef __PYX_HAVE__cython_interface
#define __PYX_HAVE__cython_interface

#include "Python.h"

#ifndef __PYX_HAVE_API__cython_interface

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void writeBVH_interface(PyObject *, PyObject *, PyObject *, PyObject *, PyObject *);

#endif /* !__PYX_HAVE_API__cython_interface */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcython_interface(void);
#else
PyMODINIT_FUNC PyInit_cython_interface(void);
#endif

#endif /* !__PYX_HAVE__cython_interface */
